#!/bin/bash
PAQUETNAME=snack

# www-data sudo configuration
# Configuration de sudo pour www-data
# Le svn ne conserve pas les droits, on pourra supprimer cela pour le paquet final
# TODO :Delete
chmod 0440 /etc/sudoers.d/snack
chown root:root /etc/sudoers.d/snack

# Cleaning the stdin buffer before reading
# Vider le buffer du stdin avant de lire

read -t 1 -n 10000 -d "" discard

# Create database + Add default admin user account
# Création de la base de donnée + Ajout d'un compte administrateur par défaut

read -s -p "Enter MySQL root password : " mdp_root
echo ""

while [ -z "$mdp_radius" -o $mdp_radius != $mdp_radius_bis ] 
do
    if [ -n "$mdp_radius" ]
    then
	echo "Password not corresponding! "
    fi

    read -t 1 -n 10000 -d '' discard
    read -s  -p "Define password for mysql user used by freeradius : " mdp_radius
    echo ""
    
    read -t 1 -n 10000 -d '' discard
    read -s -p "Re enter this password : " mdp_radius_bis
    echo ""
done

echo "	create database radius;\
	grant all on radius.* to radius@localhost identified by '$mdp_radius';\
	flush privileges;\
" | mysql -uroot -p$mdp_root

until [ $? -eq 0 ]
do
	read -t 1 -n 10000 -d "" discard
	read -s -p "Mot de passe root MySQL : " mdp_root
        echo ""
	

	echo "	create database radius;\
		grant all on radius.* to radius@localhost identified by '$mdp_radius';\
		flush privileges;\
	" | mysql -uroot -p$mdp_root
	
done

mysql -uroot -p$mdp_root radius < /etc/freeradius/sql/mysql/schema.sql
mysql -uroot -p$mdp_root radius < /etc/freeradius/sql/mysql/nas.sql

echo "INSERT INTO radcheck(UserName, Attribute, op, Value) VALUES ('admin', 'Cleartext-Password', ':=', '$mdp_radius');" | mysql -uroot -p$mdp_root radius

# Configuration de Radius pour intéragir avec la base de donnée
# Radius configuration in order to interact with our database

sed\
	-e "s/radpass/$mdp_radius/"\
	-e "s/#\(readclients\)/\1/"\
	-i /etc/freeradius/sql.conf

sed\
	-e 's/#\(\s*\$INCLUDE sql\.conf\)/\1/'\
	-e 's/#\(\s*\$INCLUDE sql\/mysql\/counter.conf\)/\1/'\
	-e 'N; s/\(#\s*clients\s*=\s*per_socket_clients.*\)\(}\)/\1\tvirtual_server = bh.consulting.net\n\2/'\
	-e 's/\(\$INCLUDE clients\.conf\)/#\1/'\
	-i /etc/freeradius/radiusd.conf

## Certificates
## Certificats

# Guess and set the home path
# Deviner et définir le chemin vers le home
if [ -n "$SUDO_USER" ];
    then
	USER_HOME=/home/$SUDO_USER
elif [ -d "/home/tech" ]
    then
	USER_HOME=/home/tech
else
	USER_HOME=$HOME
fi

echo "Using home : $USER_HOME"


DESTROOTPATH=$USER_HOME/$PAQUETNAME
DESTFOLDER=cert
DESTPATH=$DESTROOTPATH/$DESTFOLDER
SSLCNF=/etc/ssl/openssl.cnf
RADCERTVALIDITY=3650 #ten years
CACERTVALIDITY=3650 #ten years
PATHDIRMODE=0070
ONLYRADIUSACCESS=0700
INTERFACEACCESS=0770 
INTERFACETHROUGH=0710
READINGONLY=0440
ONLYINTERFACEACCESS=0700

INTERFACEUSER=www-data
RADIUSUSER=freerad


CAKEY=cakey.pem
CAREQ=careq.pem
CACERT=cacert.pem

RADIUSKEY=radius_key.pem
RADIUSREQ=radius_req.pem
RADIUSCERT=radius_cert.pem

EAPCONF=/etc/freeradius/eap.conf
DEFAULTVIRTUALSERVER=/etc/freeradius/sites-available/default
INNERTUNNELVIRTUALSERVER=/etc/freeradius/sites-available/inner-tunnel

# Get the name of the client firm
# Récupérer le nom de l'entreprise cliente

read -t 1 -n 10000 -d "" discard
read -p "Enter the name of the client (CA common name): " CLIENTNAME

# Update openssl.cnf configuration
# Mise à jour de la configuration openssl.cnf

# TODO: cela sert à quoi
sed\
	-e "s|./demoCA|$DESTPATH |"\
	-e "/\s*certificate\s*=/c certificate = \$dir/private/cacert.pem\t"\
	-i $SSLCNF

# Creation of the needed repertories
# Création des répertoires nécessaires

if test ! -d $DESTROOTPATH
then
	mkdir -p $DESTROOTPATH -m $PATHDIRMODE
fi

mkdir $DESTPATH -m $INTERFACEACCESS;
mkdir "${DESTPATH}/certs" -m $INTERFACETHROUGH;
mkdir "${DESTPATH}/crl" -m $INTERFACEACCESS ;
mkdir "${DESTPATH}/newcerts" -m $INTERFACEACCESS;
mkdir "${DESTPATH}/private" -m $INTERFACETHROUGH;
mkdir "${DESTPATH}/users" -m $INTERFACEACCESS;
# TODO: cela sert à quoi
touch $DESTPATH/index.txt
echo "01" > $DESTPATH/crlnumber

# Creation of the Authority Certificate (CA)
# Création du certificat d'autorité (CA)

openssl genrsa -out $DESTPATH/private/$CAKEY 4096 

openssl req -new -key $DESTPATH/private/$CAKEY \
	-subj /countryName=FR/stateOrProvinceName=France/localityName=Nancy/organizationName=BHConsulting/commonName="$CLIENTNAME"/ \
	-out $DESTPATH/private/$CAREQ

openssl ca -config /etc/ssl/openssl.cnf \
	-create_serial -out $DESTPATH/private/$CACERT -days $CACERTVALIDITY -batch \
	-keyfile $DESTPATH/private/$CAKEY -selfsign \
	-extensions v3_ca \
	-infiles $DESTPATH/private/$CAREQ

# Setting approriates permissions
# Affectation des permissions

chown $INTERFACEUSER $DESTPATH/private/$CAKEY
chmod $INTERFACEACCESS $DESTPATH/private/$CAKEY
# TODO: vérifier qu'on peut téléchager le CACERT avec le readonly
chmod $READINGONLY $DESTPATH/private/$CACERT

# Creation of the radius certificate
# Création du certificat authentifiant le server radius

openssl genrsa -out $DESTPATH/private/$RADIUSKEY 4096

openssl req -config /etc/ssl/openssl.cnf -new -key $DESTPATH/private/$RADIUSKEY \
	-subj /countryName=FR/stateOrProvinceName=France/localityName=Nancy/organizationName=BHConsulting/commonName=`hostname`/ \
	-out $DESTPATH/private/$RADIUSREQ -days $RADCERTVALIDITY

openssl ca -config /etc/ssl/openssl.cnf -policy policy_anything -out $DESTPATH/private/$RADIUSCERT -batch -infiles $DESTPATH/private/$RADIUSREQ

chown $RADIUSUSER $DESTPATH/private/$RADIUSKEY
chown $RADIUSUSER $DESTPATH/private/$RADIUSCERT
chmod $ONLYRADIUSACCESS $DESTPATH/private/$RADIUSKEY
chmod $ONLYRADIUSACCESS $DESTPATH/private/$RADIUSCERT

# First CRL Generation + link to permit revocation verifications
# Première génération de la CRL + permission de révocation

openssl ca -config /etc/ssl/openssl.cnf -gencrl -out $DESTPATH/crl/crl.pem

HASH=`openssl x509 -noout -hash -in $DESTPATH/private/$CACERT`
ln -s $DESTPATH/private/$CACERT $DESTPATH/certs/$HASH.0
ln -s $DESTPATH/crl/crl.pem $DESTPATH/certs/$HASH.r0


# Setting approriates permissions
# Affectation des permissions

chown $RADIUSUSER $DESTPATH/crl/crl.pem
chmod $INTERFACEACCESS $DESTPATH/crl/crl.pem

# Now, we configure the radius to use certificates
# Maintenant, on configure le radius pour qu'il utilise les certificats

# First, we must create those two file
# On doit d'abord créer ces deux fichiers

dd if=/dev/urandom of=$DESTPATH/random count=2
openssl dhparam -check -text -5 1024 -out $DESTPATH/dh

# Setting approriates permissions
# Affectation des permissions

chown $RADIUSUSER $DESTPATH/random
chown $RADIUSUSER $DESTPATH/dh
chmod $ONLYRADIUSACCESS $DESTPATH/random
chmod $ONLYRADIUSACCESS $DESTPATH/dh

# Setting the eap.conf file
# onfiguration du fichier eap.conf

# TLS
# TODO: simplifier les règles
sed\
        -e "/certdir =/i \\\t\t\tconfdir = $DESTPATH"\
        -e "/certdir =/c \\\t\t\tcertdir = \${confdir}"\
        -e "/cadir =/c \\\t\t\tcadir = \${confdir}/private"\
        -e "/private_key_password =/c \\\t\t\tprivate_key_password ="\
        -e "/private_key_file =/c \\\t\t\tprivate_key_file = \${cadir}/$RADIUSKEY"\
        -e "/^\s*certificate_file =/c \\\t\t\tcertificate_file = \${cadir}/$RADIUSCERT"\
        -e "/^\s*CA_file =/c \\\t\t\tCA_file = \${cadir}/$CACERT"\
        -e "/dh_file =/c \\\t\t\tdh_file = \${certdir}/dh"\
        -e "/check_crl =/c \\\t\t\tcheck_crl = yes"\
        -e "/^\s*#*CA_path =/c \\\t\t\tCA_path = \${certdir}/certs"\
        -e "/^\s*#*\s*check_cert_cn =/c \\\t\t\tcheck_cert_cn = %{User-Name}"\
        -i $EAPCONF

# By the way, changes for default virtual server and inner-tunnel. Used by EAP-MD5 authentication.
# TODO: vérifier à quoi ça sert
sed -e "{N 
	    s/\s*#  Read the 'users' file\n\s*files/\\t#  Read the 'users' file\n#\\tfiles/
	    }" \
	-e "{N
	    s/\s*#  See \"Authorization Queries\" in sql.conf\n\s*#\s*sql/\\t#  See \"Authorization Queries\" in sql.conf\n\\tsql/
	    }" \
	-i $DEFAULTVIRTUALSERVER

sed -e "{N 
	    s/\s*#  Read the 'users' file\n\s*files/\\t#  Read the 'users' file\n#\\tfiles/
	    }" \
	-e "{N
	    s/\s*#  See \"Authorization Queries\" in sql.conf\n\s*#\s*sql/\\t#  See \"Authorization Queries\" in sql.conf\n\\tsql/
	    }" \
	-i $INNERTUNNELVIRTUALSERVER

# Copy scripts version
# Copie des scripts

mkdir $USER_HOME/$PAQUETNAME/scripts -m $ONLYINTERFACEACCESS
cp -r scripts/* $USER_HOME/$PAQUETNAME/scripts

# Setting approriates permissions
# Affecter les permissions

chown -R $INTERFACEUSER $USER_HOME/$PAQUETNAME/scripts
chmod -R $ONLYINTERFACEACCESS $USER_HOME/$PAQUETNAME/scripts

# Setting access groups to include web interface and radius
# Nouveau groupe regroupant l'interface et le radius

groupadd snack
usermod -a -G snack $RADIUSUSER
usermod -a -G snack $INTERFACEUSER
chown -R :snack $USER_HOME/$PAQUETNAME

# Activate syslog for freeradius
# Active Syslog pour Freeradius

service syslog-ng restart
sed -e 's/\(destination\s*=\s*\).*$/\1syslog/'\
	 -e 's/\(syslog_facility\s*=\s*\).*$/\1local2/'\
	 -i /etc/freeradius/radiusd.conf
service freeradius restart

exit 0
