#!/bin/sh
PAQUETNAME=snack
USER_HOME=USER_HOME_TO_SED
DESTPATH=$USER_HOME/$PAQUETNAME/cert
USERFILESPATH=$DESTPATH/users

if [ ! $# -eq 1 ]
then
        if [ $# -gt 1 ]
        then
                echo "Usage: createClient [name]"
                echo "No more argument needed"
                exit
        else
                read -p "Enter user name: " USERNAME
        fi
else
        USERNAME=$1

fi


USERKEY=${USERNAME}_key.pem
USERCERT=${USERNAME}_cert.pem
USERREQ=${USERNAME}_req.pem
USERCERTVALIDITY=3650  # 10 years

openssl genrsa -out $USERFILESPATH/$USERKEY 4096

openssl req -config /etc/ssl/openssl.cnf -new -key $USERFILESPATH/$USERKEY \
        -subj /countryName=FR/stateOrProvinceName=France/localityName=Nancy/organizationName=BHConsulting/commonName=$USERNAME/ \
        -out $USERFILESPATH/$USERREQ -days $USERCERTVALIDITY
openssl ca -config /etc/ssl/openssl.cnf -policy policy_anything -out $USERFILESPATH/$USERCERT -batch -infiles $USERFILESPATH/$USERREQ


#CRL regeneration. Needed to pass in the revocation test.

openssl ca -config /etc/ssl/openssl.cnf -gencrl -out $DESTPATH/crl/crl.pem
