#!/bin/sh

USER_HOME=USER_HOME_TO_SED
DESTPATH=$USER_HOME/cert
USERFILESPATH=$DESTPATH/users


if [ ! $# -eq 1 ]
then
        if [ $# -gt 1 ]
        then
                echo "Usage: createClient [name]"
                echo "No more argument needed"
                exit
        else
                read -p "Enter user name: " USERNAME
        fi
else
        USERNAME=$1

fi


USERCERT=${USERNAME}_cert.pem

openssl ca -config /etc/ssl/openssl.cnf -revoke $USERFILESPATH/$USERCERT


#CRL regeneration.

openssl ca -config /etc/ssl/openssl.cnf -gencrl -out $DESTPATH/crl/crl.pem
