#!/bin/bash

userdel -r snack
groupdel snack

ln -s /etc/apache2/sites-available/default /etc/apache2/sites-enabled/000-default

unlink /etc/apache2/sites-enabled/snack
rm -fr /etc/apache2/sites-available/snack
rm -fr /etc/sudoers.d/snack
rm -fr /home/snack

service apache2 restart

exit 0
